_wandb:
    value:
        cli_version: 0.21.3
        e:
            gu68e79yfaf0k4bnk63d2z44u5vl7cy1:
                codePath: test_fixes.py
                codePathLocal: test_fixes.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "153394081792"
                        used: "82847129600"
                email: fatmakaracaerdogan@gmail.com
                executable: C:\Users\fatma\AppData\Local\Programs\Python\Python311\python.exe
                host: LAPTOP-PIOUJ1OI
                memory:
                    total: "7448702976"
                os: Windows-10-10.0.26100-SP0
                program: D:\VoiceBridge_Realtime_App\test_fixes.py
                python: CPython 3.11.0
                root: D:\VoiceBridge_Realtime_App
                startedAt: "2025-09-10T09:29:17.318215Z"
                writerId: gu68e79yfaf0k4bnk63d2z44u5vl7cy1
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
                - 95
            "3":
                - 13
                - 15
                - 16
            "4": 3.11.0
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
api_version:
    value: 1.0.0
framework:
    value: fastapi
language:
    value: english
model_type:
    value: whisper
