_wandb:
    value:
        cli_version: 0.21.3
        e:
            4afsvhii81qx5zaefnxe4b9zru5yxp4c:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "153394081792"
                        used: "82845880320"
                email: fatmakaracaerdogan@gmail.com
                executable: C:\Users\fatma\AppData\Local\Programs\Python\Python311\python.exe
                host: LAPTOP-PIOUJ1OI
                memory:
                    total: "7448702976"
                os: Windows-10-10.0.26100-SP0
                program: <python with no main file>
                python: CPython 3.11.0
                root: D:\VoiceBridge_Realtime_App
                startedAt: "2025-09-10T09:14:43.539306Z"
                writerId: 4afsvhii81qx5zaefnxe4b9zru5yxp4c
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 5
                - 53
                - 95
            "2":
                - 5
                - 53
                - 95
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.0
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
api_version:
    value: 1.0.0
framework:
    value: fastapi
language:
    value: english
model_type:
    value: whisper
