global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "voicebridge_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'voicebridge-api'
    static_configs:
      - targets: ['voicebridge_backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'voicebridge-prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'voicebridge-redis'
    static_configs:
      - targets: ['voicebridge_redis:6379']

  - job_name: 'voicebridge-node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
